language: ruby
rvm:
- 2.0.0
- 2.3.0
- 2.4.0
- 2.5.0
script: bundle exec rspec
before_install:
- gem update bundler
deploy:
  provider: rubygems
  api_key:
    secure: O7YI3MNFgWH9xrjpTaYu6zvfhgpgQrMQullQebWR9B7sHXUw69XRW4mSy6PdsAHhFddymmfIWBW1rqS5HhiO7I50r/o/S90Oqy2vftQ3Fm8EXhKywc60r6o60EUOiqw/QObnqT/yspX0PpJ4uGlkDpc6XoDY/01QvhvoK13TnS4=
  gem: mathpack
  on:
    branch: master
    repo: maxmilan/mathpack
notifications:
  email: false
